### PR TITLE
feat: Added OpenAI Whisper STT provider using Whisper.Net library

### PR DESCRIPTION
**Pull request by Lyx52**
Added simple local OpenAI whisper chain provider using existing Whisper.Net library

### CODE REVIEW

**Comment by HavenDV** [comment]
Hello. Good job! Can we immediately think about what will happen if the user wants to use Whisper.net.Runtime.CoreML? Will this be possible in the current implementation or can only one Runtime be specified in the dependencies. I think we have a similar scenario for LlamaSharp

image

**Comment by HavenDV** [comment]
Also we have some problem with test:
```
Error: System.IO.FileNotFoundException : Could not find file '/home/runner/work/LangChain/LangChain/src/Providers/WhisperNet/test/bin/Release/net8.0/.\Resources\kennedy.wav'.

  Failed TestWhisperSTT [1 s]
```

**Comment by Lyx52** [comment]
> Hello. Good job! Can we immediately think about what will happen if the user wants to use Whisper.net.Runtime.CoreML? Will this be possible in the current implementation or can only one Runtime be specified in the dependencies. I think we have a similar scenario for LlamaSharp
> 
> image

Hi! Yes, I see that CoreML backend seems to need extra files next to model files, I can add extra boolean flag to DownloadModel function

**Comment by Lyx52** [comment]
> My main point is that will there be any problems if we specify two runtime dependencies at the same time? As far as I know, for LLamaSharp you need to specify either one or the other, two together will not work. And, accordingly, if we specify a dependency in our package, the user is blocked from using the second option

It seems like its the same for Whisper.Net and it only supports one backend at a time, but it should be fine since Whisper.net.Runtime is only a dependency for tests

**Comment by HavenDV** [comment]
@all-contributors please add @Lyx52 for infrastructure, tests and code

**Comment by HavenDV** [comment]
@Lyx52 I can add you to the list of contributors in the Discord channel. This will give you access to our dev chat, in which other contributors and I discuss the development of the library/offer ideas. What is your Discord name?

**Comment by Lyx52** [comment]
> @Lyx52 I can add you to the list of contributors in the Discord channel. This will give you access to our dev chat, in which other contributors and I discuss the development of the library/offer ideas. What is your Discord name?

My Discord username is Lyx.#

**Pull request merged**
