### PR TITLE
Added support for Azure OpenAI provider

### PR DESCRIPTION
**Pull request by kharedev247**
Added support for Azure OpenAI provider

Issue: #24

### CODE REVIEW

**Comment by HavenDV** [comment]
@all-contributors please add @kharedev247 for infrastructure, tests and code

**Comment by brandonh-msft** [comment]
@HavenDV  / @kharedev247 
Any idea when we can expect a release w/ this? As-is the latest 0.12.2 release does not appear to work with Azure.

**Comment by HavenDV** [comment]
We made significant changes to the preview version and have been polishing it for a while, but I think it's ready for the next release this weekend.
At the moment it is better to use the latest preview version to prepare for this

**Comment by HavenDV** [comment]
https://github.com/tryAGI/LangChain/releases/tag/v0.13.0
We finally released it. There may still be errors here and we are actively monitoring this and are ready for feedback.
We will try to release stable versions more often in the future (about once a month)
Right now I'm primarily focusing on abstractions to avoid breaking changes in the future.

**Pull request merged**
